import swaggerJsdoc from 'swagger-jsdoc';

const options = {
  // List of files to be processed.
  apis: ['./routes/account.js'],
  // You can also set globs for your apis
  // e.g. './routes/*.js'
  basePath: '/account',
  swaggerDefinition: {
    info: {
      description: 'Test API with autogenerated swagger doc',
      title: 'Accounts API',
      version: '1.0.0',
    },
  },
};

const specs = swaggerJsdoc(options);

export default specs;
